name: Docker Image CI

on:
  push:
    branches: [ main, dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get 
      run: echo "image_name=`grep -E "ENV IMAGE_NAME=" ./Dockerfile | sed 's/^ENV IMAGE_NAME=\"\([^ ]*\)\"/\1/'`" >> $GITHUB_ENV

    - name: Build Docker Image (base)
      run: |
        echo ${{env.image_name}}
        docker build . --no-cache=true --tag jpvantassel/${{env.image_name}}
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Push Docker Image (base)
    #   run: |
    #     echo ${{env.image_name}}
    #     docker push jpvantassel/${{env.image_name}}
